introduce a failure to workflow

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -35,3 +35,10 @@ jobs:
       # Add my own custom step
       - name: Add another step
         run: echo "Added my own custom step"
+
+      # Cause a failure
+      - name: Cause a failure
+        run: |
+          echo "This should fail"
+          exit 1
+
